server {
    listen 80;
    server_name localhost;

    # 托管 Django 收集的静态文件（路径与 STATIC_ROOT 一致）
    location /static/ {
        alias /usr/src/app/staticfiles/;
        expires 30d;  # 静态文件缓存 30 天
    }

    location / {
        proxy_pass http://sxzslz:8000;  # web 是 Docker Compose 中 Django 服务的名称
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;  # 关键：传递协议（http/https）
    }

}