server {
    listen 80;
    server_name localhost;

    location / {
        proxy_pass http://sxzslz:8000;  # web 是 Docker Compose 中 Django 服务的名称

        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
        proxy_set_header Origin $http_origin; 
    }

    location /static/ {
        alias /usr/src/app/staticfiles/;
        expires 30d;  # 静态文件缓存 30 天
    }

}