# Generated by Django 5.2.4 on 2025-07-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_article_title_alter_user_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='read',
            field=models.IntegerField(default=0),
        ),
    ]
