# Generated by Django 5.2.4 on 2025-07-20 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_article_read'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '文章列表', 'verbose_name_plural': '文章'},
        ),
        migrations.AlterModelOptions(
            name='subset',
            options={'verbose_name': '文章类别列表', 'verbose_name_plural': '文章类别'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户列表', 'verbose_name_plural': '编辑用户'},
        ),
    ]
